### ISSUE TITLE
서버 reload시 maxplayer가  adminCount만큼 빠지는 버그

### ISSUE THREAD

**Issue by underconnor** [qogusdn1017/Advancement-Traveler#7]
플러그인이 disable 될때 server.maxPlayers - adminCount 값이 config에 저장되는데, 서버가 stop일때에는 정상적인 코드이지만 reload 진행시 adminCount가 빠져 어드민이 reload 실행후 서버를 나갈때 server.maxPlayers가 server.maxPlayers-adminCount 가 된다.

ex)
1. max player = 10 
2. 어드민 접속, maxplayer = 11
3.  reload 실행
4. server.maxPlayers - adminCount = 11-1 = 10
5. 어드민 나감, --max player = 10-1=9 
6. 초기 max player != 현재 maxplayer (10 != 9)

**Comment by qogusdn1017** [comment]
리로드는 저도 압니다 패치할거임
